package cadelac.framework.blade.core.exception;

/**
 * This exception is generated by errors committed by the framework itself.
 * @author cadelac
 *
 */
public class SystemException extends FrameworkException {
	/**
	 * 
	 */
	private static final long serialVersionUID = -3105572948018482102L;

	public SystemException(final String text_)  {
		super(text_);
	}
}
